import { CommodityCategory } from "@/types/inspection";

// Standard Units of Measurement according to Rule 12 & Second Schedule of Legal Metrology (Packaged Commodities) Rules, 2011
export const VALID_MASS_UNITS = ["g", "g.", "gm", "gms", "gram", "grams", "kg", "kg.", "kilogram", "kilograms", "mg", "milligram"];
export const VALID_VOLUME_UNITS = ["ml", "ml.", "millilitre", "millilitres", "l", "l.", "ltr", "litre", "litres", "kl"];
export const VALID_LENGTH_UNITS = ["cm", "m", "metre", "metres", "mm"];
export const VALID_AREA_UNITS = ["sq. cm", "sq. m", "sq m", "sq cm"];
export const VALID_COUNT_UNITS = ["u", "unit", "units", "n", "number", "num", "no.", "no", "piece", "pieces", "pc", "pcs", "count"];

export const ALL_VALID_UNITS = [
  ...VALID_MASS_UNITS,
  ...VALID_VOLUME_UNITS,
  ...VALID_LENGTH_UNITS,
  ...VALID_AREA_UNITS,
  ...VALID_COUNT_UNITS,
];

// Ambiguous non-compliant qualifying words prohibited under Rule 13
export const PROHIBITED_QUANTITY_QUALIFIERS = [
  "approx",
  "approx.",
  "approximately",
  "when packed",
  "around",
  "net weight when packed",
  "about",
  "minimum",
  "min.",
  "+/-",
  "plus minus",
  "nominal",
];

// Standard Categories in Indian Legal Metrology
export const COMMODITY_CATEGORIES: CommodityCategory[] = [
  "Food & Beverages",
  "Cosmetics & Personal Care",
  "Pharmaceuticals & Healthcare",
  "Household & Cleaning",
  "Electronics & Appliances",
  "Apparel & Textiles",
  "General Packaged Commodities",
];

// Prototype disclaimer requirement
export const PROTOTYPE_LEGAL_DISCLAIMER =
  "Prototype compliance assessment based on configured rules. This report is generated by a prototype software system for demonstration and preliminary assessment. It does not constitute legal certification or an official Legal Metrology inspection under the Legal Metrology Act, 2009.";
